sudo: required
dist: xenial
language: rust
cache:
  apt: true
  cargo: true
rust:
  - nightly
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

before_script:
  - rustup component add rustfmt
script:
  - cargo build --verbose --all
  - RUST_BACKTRACE=1 cargo test --verbose --all
  - cargo fmt -- --check
after_success:
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  make coverage
