[package]
name = "rxui_rx"
version = "0.1.0"
authors = ["Alexander Linne <alexander.linne@outlook.com>"]
edition = "2018"

[dependencies]
derive-new = "0.5"
parking_lot = "0.11.0"
rxui_rx_derive = { path = "../rxui_rx_derive" }
threadpool = "1.8.1"
