[package]
name = "kled"
version = "0.1.0"
authors = ["Alexander Linne <alexander.linne@outlook.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
derive-new = "0.5"
num_cpus = "1.13"
parking_lot = { version = "0.11" }
kled_derive = { path = "../kled_derive" }
